version: '3.9'
services:
  dynamodb-local:
    container_name: dynamodb-local
    image: amazon/dynamodb-local:latest
    ports:
      - '8000:8000'
    volumes:
      - dynamodb-data:/home/dynamodblocal
    networks:
      - dynamodb-network
    # command: 'aws dynamodb create-table --cli-input-json file://table-script.json --endpoint-url http://localhost:8000'

networks:
  dynamodb-network:
    driver: bridge

volumes:
  dynamodb-data:
